---

- name: uninstall legacy packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: install requirements
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - device-mapper-persistent-data
    - lvm2
    - epel-release

- name: install pip
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip

- name: install docker-py
  pip:
    name: "{{ item }}"
  with_items:
  - docker

- name: add docker rpm key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  when: docker_yum_gpgcheck == True

- name: add docker frepository
  yum_repository:
    name: docker
    description: docker repository
    file: docker
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: "{{ docker_yum_gpgcheck }}"

- name: install docker
  yum:
    name: docker-ce
    state: present
